<div class="footer">
<p>
<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/deed.de">
<img alt="Creative Commons License BY-NC-SA" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png" /></a>
</p>
<p>
<?php
echo Date("F d Y H:i")."\n";
?>
<br>
Generated by <a href="http://www.php.net/">PHP</a> and the <a href="ellislab.com/codeigniter">CodeIgniter</a> PHP Framework<br>
Using <a href="http://jquery.com/" >jQuery</a>, JavaScript-SHA1 from <a href="http://www.webtoolkit.info">webtoolkit.info</a>
</p>
</div>	
</body>
</html>