<div style="clear:both;"></div>
<div class="footer">
<p>
<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/deed.de">
<img alt="Creative Commons License BY-NC-SA" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png" /></a>
</p>
<p>
<?php
echo Date("F d Y H:i")."\n";
?>
<ul>
	<li><a href="<?php echo $this->config->item('base_url');?>/timf/view/start">Start</a></li>
	<li><a href="<?php echo $this->config->item('base_url');?>/timf/view/about">About</a></li>
	<?php 
		if($this->session->userdata('loggedin')) {
			echo '<li><a href="'.base_url('timf/view/profile').'">Profil</a></li>'."\n";
			echo '<li><a href="'.base_url('timf/logout').'">Logout</a></li>'."\n";
		}
	?>
</ul>
<br>
Generated by <a target="_blank" href="http://www.php.net/">PHP</a> and the <a href="http://ellislab.com/codeigniter" target="_blank">CodeIgniter</a> PHP Framework<br>
Using <a href="http://jquery.com/" target="_blank">jQuery</a> and JavaScript-SHA1 (from <a href="http://www.webtoolkit.info" target="_blank">webtoolkit.info</a>)<br>
Organisation with <a href="http://git-scm.com" target="_blank">Git</a> and <a href="https://github.com" target="_blank">GitHub</a> <a href="https://github.com/criztovyl/timf" target="_blank">(timf@GitHub)</a><br>
Made with <a href="http://bluefish.openoffice.nl/" target="_blank">Bluefish</a><br>
Powered by <a href="http://www.ubuntu.com/server" target="_blank">Ubuntu (Server)</a> and <a href="http://debian.org" target="_blank">Debian</a>
</p>
</div>	
</body>
</html>